services:
  # Backend service
  - type: web
    name: ai-career-backend
    env: node
    branch: main
    plan: free
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: "<your-mongo-uri>"
      - key: JWT_SECRET
        value: "mysupersecret"
      - key: PORT
        value: "5000"

  # Frontend service
  - type: web
    name: ai-career-frontend
    env: node
    branch: main
    plan: free
    buildCommand: "cd front-end && npm install && npx vite build"
    startCommand: "cd front-end && npx serve -s vite-project/dist -l $PORT"
    autoDeploy: true
